DECLARE
CURSOR CHUNCHO IS SELECT REGNO,NAME FROM STUDENT;
REGNO1 STUDENT.REGNO%TYPE;
NAME1 STUDENT.NAME%TYPE;
BEGIN
OPEN CHUNCHO;
FETCH CHUNCHO INTO REGNO1,NAME1;
DBMS_OUtPUT.PUT_LINE('REGISTRATION NO. : '||REGNO1);
DBMS_OUtPUT.PUT_LINE('NAME :'||NAME1);
CLOSE CHUNCHO;
END;